services:

  api-gateway:
    container_name: api-gateway
    build:
      context: ./backend/api
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    depends_on:
      - api-mongodb
    links:
      - api-mongodb

  users-app:
    container_name: users-app
    build:
      context: ./backend/users_app
      dockerfile: Dockerfile 
    ports:
      - "3005:3005"
    depends_on:
      - users-mongodb
    links:
      - users-mongodb

  plans-app:
    container_name: plans-app
    build:
      context: ./backend/plans_app
      dockerfile: Dockerfile 
    ports:
      - "3004:3004"
    depends_on:
      - plans-mongodb
    links:
      - plans-mongodb

  projects-app:
    container_name: projects-app
    build:
      context: ./backend/projects_app
      dockerfile: Dockerfile 
    ports:
      - "3003:3003"
    depends_on:
      - projects-mongodb
      - images-app
    links:
      - projects-mongodb
      - images-app

  images-app:
    container_name: images-app
    build:
      context: ./backend/images_app
      dockerfile: Dockerfile 
    ports:
      - "3002:3002"
    depends_on:
      - images-mongodb
    links:
      - images-mongodb

  tools-app:
    container_name: tools-app
    build:
      context: ./backend/tools_app
      dockerfile: Dockerfile 
    ports:
      - "3001:3001"
    depends_on:
      - tools-mongodb
    links:
      - tools-mongodb

  users-mongodb:
    container_name: users-db
    image: mongo:latest
    ports:
      - "27005:27017"

  plans-mongodb:
    container_name: plans-db
    image: mongo:latest
    ports:
      - "27004:27017"
    depends_on:
      - plans-mongo-seed

  projects-mongodb:
    container_name: projects-db
    image: mongo:latest
    ports:
     - "27003:27017"

  images-mongodb:
    container_name: images-db
    image: mongo:latest
    ports:
      - "27002:27017"

  tools-mongodb:
    container_name: tools-db
    image: mongo:latest
    ports:
      - "27001:27017"
    depends_on:
      - tools-mongo-seed
  
  api-mongodb:
    container_name:  api-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"

  plans-mongo-seed:
    image: mongo:latest
    volumes:
      - ./backend/db/plans.json:/plans.json
    command: mongoimport --host plans-db --port 27017 -d picturas-plans -c plans --type json --file /plans.json --jsonArray

  tools-mongo-seed:
    image: mongo:latest
    volumes:
      - ./backend/db/tools.json:/tools.json
    command: mongoimport --host tools-db --port 27017 -d picturas-tools -c tools --type json --file /tools.json --jsonArray