services:

  projects-app:
    container_name: projects-app
    build:
      context: ./projects_app
      dockerfile: Dockerfile 
    ports:
      - "3003:3003"
    depends_on:
      - projects-mongodb
    links:
      - projects-mongodb

  images-app:
    container_name: images-app
    build:
      context: ./images_app
      dockerfile: Dockerfile 
    ports:
      - "3002:3002"
    depends_on:
      - images-mongodb
    links:
      - images-mongodb

  tools-app:
    container_name: tools-app
    build:
      context: ./tools_app
      dockerfile: Dockerfile 
    ports:
      - "3001:3001"
    depends_on:
      - tools-mongodb
    links:
      - tools-mongodb

  projects-mongodb:
    container_name: projects-db
    image: mongo:latest
    # ports:
    #  - "27003:27017"

  images-mongodb:
    container_name: images-db
    image: mongo:latest
    # ports:
    #   - "27002:27017"

  tools-mongodb:
    container_name: tools-db
    image: mongo:latest
    # ports:
    #   - "27001:27017"
    depends_on:
      - tools-mongo-seed

  tools-mongo-seed:
    image: mongo:latest
    volumes:
      - ./tools.json:/tools.json
    command: mongoimport --host tools-db --port 27017 -d picturas-tools -c tools --type json --file /tools.json --jsonArray