services:

#  tools-managment:
#    container_name: tools-managment
#    build:
#      context: ./tools_management
#      dockerfile: Dockerfile 
#    environment:
#      - TOOLS_FLASK_HOST=0.0.0.0
#      - TOOLS_FLASK_PORT=5000
#      - MONGO_HOST=mongodb
#      - MONGO_PORT=27017
#      - PICTURAS_DB=picturas
#    ports:
#      - "5000:5000"
#    depends_on:
#      - mongodb
#    links:
#      - mongodb

  mongodb:
    container_name: picturasdb
    image: mongo:latest
    ports:
     - "27017:27017"
    depends_on:
      - mongo-seed

  mongo-seed:
    image: mongo:latest
    volumes:
      - ./tools.json:/tools.json
    command: mongoimport --host mongodb -d picturas -c tool --type json --file /tools.json --jsonArray